### ISSUE TITLE
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'

### ISSUE THREAD

**Issue by stefanocovino** [djones1040/PythonPhot#11]
Hello,

I am reporting a new problem, likely due to the evolution of some library rather than to PythonPhot.

If I try to compile the library under python 3.5 (anaconda distribution) I see the following error message:

[Mac-Mini-di-Stefano:~/ownCloud/Pacchetti/PythonPhot-master_old] covino% pit3 setup.py install
The requested path 'astropy_helpers' for importing astropy_helpers does not exist, or does not contain a copy of the astropy_helpers package.  Attempting download instead.
Downloading astropy_helpers; run setup.py with the --offline option to force offline installation.
/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/Users/covino/owncloud/Pacchetti/anaconda3/lib/python3.5/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Traceback (most recent call last):
  File "setup.py", line 25, in <module>
    conf = config.ConfigParser()
AttributeError: module 'distutils.config' has no attribute 'ConfigParser'

Nothing like that happened for python 3.3.

Thanks anyway,
  Stefano

**Comment by djones1040** [comment]
Hi Stefano,

Sorry for my slow response, you caught me on a vacation.  Yep, the distutils library has evolved.  I don't have python 3.5 on any machines, but it appears that ConfigParser -> RawConfigParser in the latest version.  I just added a try/except statement as a quick fix.  Can you let me know if it works?  Thanks,

David

**Comment by stefanocovino** [comment]
> Hi Stefano,
> 
> Sorry for my slow response, you caught me on a vacation. Yep, the distutils library has evolved. I don't have python 3.5 on any machines, but it appears that ConfigParser -> RawConfigParser in the latest version. I just added a try/except statement as a quick fix. Can you let me know if it works? Thanks,
> 
> David
> 
> Dear David,

yes it works. 

Thanks a lot as usual.

```
Stefano
```

**Comment by abigailStev** [comment]
Hi! This helped me fix an install issue I was having with astroquery!
