### ISSUE TITLE
extendbox - different for x and y

### ISSUE THREAD

**Issue by mcoughlin** [djones1040/PythonPhot#12]
Is there a possibility to make an optional version of extendbox which takes two different numbers, one for x and one for y? We have a use case where the error in the guess for x is much worse than that for y, and making a huge box is leading the code to find focal plane transients instead of the stars of interest.

**Comment by djones1040** [comment]
Sure!  I've just implemented that.  Let me know if it works for you.

**Comment by mcoughlin** [comment]
It works great! thank you!
