### ISSUE TITLE
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

### ISSUE THREAD

**Issue by stefanocovino** [djones1040/PythonPhot#14]
Hi,

I am running PythonPhot on a linux system running python3.6 with anaconda, and I guess there is an issue due to python3.6. I report below the error message I get:

  File "/usr/local/anaconda3/lib/python3.6/site-packages/PythonPhot-1.0.dev0-py3.6-linux-x86_64.egg/PythonPhot/aper.py", line 286, in aper
    skymod, skysig, skyskw = mmm.mmm(skybuf,readnoise=readnoise,minsky=minsky)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/PythonPhot-1.0.dev0-py3.6-linux-x86_64.egg/PythonPhot/mmm.py", line 149, in mmm
    skymed = 0.5*sky[(minimm+maximm+1)/2] + 0.5*sky[(minimm+maximm)/2 + 1] #median 
IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

Bye,
  Stefano

**Comment by stefanocovino** [comment]
Hello!

Is the package no more maintained?

Bye,
  Stefano

**Comment by djones1040** [comment]
Hi Stefano,

Thanks for the reminder, and sorry for forgetting about this.  I tried a quick fix, can you let me know if it works?  I just changed that line to:

 skymed = 0.5*sky[int((minimm+maximm+1)/2)] + 0.5*sky[int((minimm+maximm)/2 + 1)] #median

If that doesn't work, I just need to install Python 3.6 and then I can take another look at this bug.  Thanks,

David

**Comment by stefanocovino** [comment]
__________________

Mobilis in mobile

> Il giorno 16 ago 2017, alle ore 19:42, David Jones <notifications@github.com> ha scritto:
> 
> Hi Stefano,
> 
> Thanks for the reminder, and sorry for forgetting about this. I tried a quick fix, can you let me know if it works? I just changed that line to:
> 
> skymed = 0.5sky[int((minimm+maximm+1)/2)] + 0.5sky[int((minimm+maximm)/2 + 1)] #median
> 
> If that doesn't work, I just need to install Python 3.6 and then I can take another look at this bug. Thanks,
> 
> David
> 

Hi David,

yes, meanwhile I also tried to "quick-fix" the code and it seems that the problem is just in a stricter discipline for the array indices.
I had to force to int the indices here too:

            while ((j > 0) and (k < nsky-1) and \
                       ( ((sky[int(L)] - sky[int(j)]) < R) or ((sky[int(k)] - sky[int(M)]) < R))):
                j -= 1
                k += 1

        skymed = np.sum(sky[int(j):int(k+1)])/(k-j+1)

and now it seems to work.

By the way, in this expression:
> skymed = 0.5sky[int((minimm+maximm+1)/2)] + 0.5sky[int((minimm+maximm)/2 + 1)] 
> 

we first have (minimm+maximm +1)/2 and then (minimm+maximm)/2+1. Is that correct?

Thanks a lot,
   Stefano

**Comment by djones1040** [comment]
OK, I just applied and pushed your other fixes.  The skymed expression is correct, I just double checked - it’s just taking the median sky.
