### ISSUE TITLE
Again array indices are expected to be int in python3.5 and later

### ISSUE THREAD

**Issue by stefanocovino** [djones1040/PythonPhot#15]
Hi,

I am sorry to bore you again, but we have a case similar to what I have already reported recently.

In file get_psf at lines 181 and 331 we have arrays and their indices should all be int.
I have cast them with a simple int(index) as:

f = image[int(ly):int(uy+1),int(lx):int(ux+1)] - sky[int(istar)]

and

f = image[int(ly):int(uy+1),int(lx):int(ux+1)]

Probably it exists a more elegant solution but this workaround seems to work.

Bye,
   Stefano

**Comment by djones1040** [comment]
ok, I implemented your workaround!
