### ISSUE TITLE
list and float

### ISSUE THREAD

**Issue by stefanocovino** [djones1040/PythonPhot#16]
It's still me... :)

I got this (python 3.6.1):

PythonPhot/aper.py", line 208, in aper
    (yc<0.5) | (yc>nrow-1.5), 1, 0 )
TypeError: '<' not supported between instances of 'list' and 'float'

I solved it naively with:

    badstar = np.where( (np.array(xc)<0.5) | (np.array(xc)>np.array(ncol)-1.5) |
                        (np.array(yc)<0.5) | (np.array(yc)>np.array(nrow)-1.5), 1, 0 )

Cheers,
   Stefano

**Comment by djones1040** [comment]
OK, I tried a different fix to make sure xc and yc are already arrays.  Could you see if this works?
