### ISSUE TITLE
Bug in aper.py

### ISSUE THREAD

**Issue by stefanocovino** [djones1040/PythonPhot#21]
Hi,

possibly I found a tiny bug in aper.py.

Line 139. if isinstance(yc, list): xc = np.array(yc)

I guess it should be:
if isinstance(yc, list): yc = np.array(yc)

Bye,
   Stefano

**Comment by djones1040** [comment]
Hi Stefano, 

wow, thanks!  that must have been there for a while.  Fixed now.
